on:
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/flat.yml
      - ./postprocess.ts
  schedule:
    - cron: 0 0 * * *
jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.gov.uk/guidance/red-amber-and-green-list-rules-for-entering-england
          downloaded_filename: index.html
          postprocess: ./postprocess.ts
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GOOGLE_RATE_LIMIT: ${{ secrets.GOOGLE_RATE_LIMIT }}
